version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cryto_postgres
    restart: always
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d crypto_db']
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crypto_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRES: 'False'
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - crypto_network
    depends_on:
      postgres:
        condition: service_healthy
  
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  
networks:
  crypto_network:
    driver: bridge
